name: Generate Tab
on:
  push:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  generate-tab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - id: generate
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_UPDATE_ID: ${{ vars.GIST_UPDATE_ID }}
        run: |
          bun run index.ts
          echo "date=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - uses: EndBug/add-and-commit@v9
        with:
          message: '[GHA] Update generated tab (${{ steps.generate.outputs.date }})'
          push: true
